CREATE TABLE CATEGORY 
( 
  ID INT NOT NULL 
, TYPE VARCHAR(20) NULL DEFAULT user 
, CONSTRAINT PRIMARY KEY ( ID ) );

CREATE TABLE HISTORY_EVEN 
( 
  ID INT NOT NULL 
, STB INT NOT NULL 
, VERSION_FW INT NULL 
, DATE_CONNCET DATETIME NULL 
, CONSTRAINT PRIMARY KEY ( ID ) );

CREATE TABLE HISTORY_ODD 
( 
  ID INT NOT NULL 
, STB INT NOT NULL 
, VERSION_FW INT NOT NULL 
, DATE_UPDATE DATETIME NULL 
, CONSTRAINT PRIMARY KEY ( ID ) );

CREATE TABLE REGISTER_FW 
( 
  ID INT NOT NULL 
, FABRICATE VARCHAR(255) NULL 
, MODEL VARCHAR(255) NULL 
, VERSION VARCHAR(255) NULL 
, CODE_PATCH VARCHAR(255) NULL 
, MANUAL_PATH VARCHAR(255) NOT NULL 
, CATEGORY INT NULL 
, DATE_FW DATETIME NULL 
, CONSTRAINT PRIMARY KEY ( ID ) );

CREATE TABLE STB 
( 
  ID INT NOT NULL 
, MAC VARCHAR(17) NULL 
, CATEGORY INT NULL 
, VERSION_FW INT NULL 
, CONSTRAINT PRIMARY KEY ( ID ) );

ALTER TABLE HISTORY_EVEN ADD CONSTRAINT FW_FK1 FOREIGN KEY ( VERSION_FW )
 REFERENCES REGISTER_FW ( ID );

ALTER TABLE HISTORY_EVEN ADD CONSTRAINT STB_FK1 FOREIGN KEY ( STB )
 REFERENCES STB ( ID );

ALTER TABLE HISTORY_ODD ADD CONSTRAINT FW_FK1 FOREIGN KEY ( VERSION_FW )
 REFERENCES REGISTER_FW ( ID );

ALTER TABLE HISTORY_ODD ADD CONSTRAINT STB_FK1 FOREIGN KEY ( STB )
 REFERENCES STB ( ID );

ALTER TABLE REGISTER_FW ADD CONSTRAINT INFO_FW_FK1 FOREIGN KEY ( CATEGORY )
 REFERENCES CATEGORY ( ID );

ALTER TABLE STB ADD CONSTRAINT CATEGORY_FK1 FOREIGN KEY ( CATEGORY )
 REFERENCES CATEGORY ( ID );

ALTER TABLE STB ADD CONSTRAINT VERSION_FK1 FOREIGN KEY ( VERSION_FW )
 REFERENCES REGISTER_FW ( ID );

CREATE INDEX STB_INDEX1 ON STB ( ID ASC);
